POST http://localhost:8080/auth/register
Content-Type:  application/json

{
    "firstName":"Qismet",
    "lastName": "Kamilov",
    "email":"kamilov.ismet@gmail.com",
    "role":"Admin",
    "password": "qismet123"

}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "mail":"kamilov.ismet@gmail.com",
    "password": "qismet123"   
}

###
GET http://localhost:8080/mail/sendmail?to=kamilovvqismet@gmail.com&text=salamm