POST http://localhost:8080/auth/register
Content-Type:  application/json

{
    "firstName":"Qismet",
    "lastName": "Kamilov",
    "email":"kamilovvqismet@gmail.com",
    "role":"Admin",
    "password": "qismet123"

}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "mail":"kamilovvqismet@gmail.com",
    "password": "qismet123"   
}


###
POST http://localhost:8080/user/user/save
Content-Type: application/json

{
    "firstName":"Fidan",
    "lastName":"Muradova",
    "email":"muradovafidan@gmail.com",
    "password":"fidan123",
    "role":"User",
    "status":"Active"
}

###
PUT http://localhost:8080/user/uptadeUser
Content-Type: application/json

{
    "firstName":"Fidan",
    "lastName":"Muradova",
    "email":"muradovafidan@gmail.com",
    "password":"fidan123"
}

###
POST http://localhost:8080/mail/mail/save
Content-Type: application/json

{

}


###
PUT http://localhost:8080/account/increaseBalance?id=1&balance=15


###
PUT http://localhost:8080/account/decraseBalance?id=1&balance=15


###
PUT http://localhost:8080/Expense/new-expense?accountId=1&amount=15


###
GET http://localhost:8080/income/all


###
PUT http://localhost:8080/income/income/add?userId=1&amount=20


###
GET http://localhost:8080/user/user/email?email=qismet600@gmail.com


###
GET http://localhost:8080/mail/sendmail?to=kamilovvqismet@gmail.com&text=salamm